[project]
name = "pandora"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "angr>=9.2.182",
    "ansi2html>=1.9.2",
    "dominate>=2.9.1",
    "json5>=0.12.1",
    "typer>=0.20.0",
]
